import Head from "next/head";
import SlickSlider from "@/components/performance/SlickSlider";
import { styled } from "styled-components";
import connectDB from "lib/server/config/connectDB";
import Product from "lib/server/models/Product";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import { slideImages } from "../data/slide-images";

export async function getStaticProps({ req }: any) {
  console.log("\n[/] 홈페이지 정적 생성중...");

  await connectDB();
  const randomProducts = await Product.aggregate([{ $sample: { size: 9 } }]).exec();
  const recentProducts = await Product.aggregate([
    { $sort: { createdAt: -1 } },
    { $limit: 12 },
  ]).exec();
  const products = { randomProducts, recentProducts };

  return { props: { products: JSON.parse(JSON.stringify(products)) } };
}

export default function Home({ products }: any) {
  console.log("test1");
  const { randomProducts, recentProducts } = products;
  const [deviceEnv, setDeviceEnv] = useState("web");

  const randomItems = randomProducts.map((product: any) => ({
    id: product._id,
    url: product.images[0].url,
    text: product.name,
  }));
  const recentItems = recentProducts.map((product: any) => ({
    id: product._id,
    url: product.images[0].url,
    text: product.name,
  }));

  useEffect(() => {
    console.log("test2");
    const handleResize = () => {
      if (window.innerWidth <= 500) {
        setDeviceEnv("mobile");
      } else if (window.innerWidth <= 1000) {
        setDeviceEnv("tablet");
      } else {
        setDeviceEnv("web");
      }
    };

    // 페이지 로드 및 화면 크기 변경 이벤트에 대한 이벤트 리스너 등록
    handleResize(); // 페이지 로드시 초기 설정 적용
    window.addEventListener("resize", handleResize);

    return () => window.removeEventListener("resize", handleResize);
  }, []);

  return (
    <>
      <Head>
        <title>commerce-next-app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main className="home-page">
        <section className="banner">
          <SlickSlider
            items={slideImages}
            itemSize={{ width: 1000, height: 1000 }}
            sliderSize={{ height: 300 }}
            settings={{
              centerMode: true,
              slidesToShow: 1,
              centerPadding: 0,
              dots: true,
              autoplay: true,
              pauseOnHover: true,
              // speed: 1000,
              // autoplaySpeed: 5000,
            }}
          />
        </section>
        <section className="category">
          <div className="card box">
            <h1>Electronics</h1>
            <Link href={"/products?category=electronics"}>
              <Image src={"/images/category/electronics.jpg"} alt="alt" width={300} height={300} />
            </Link>
          </div>
          <div className="card box">
            <h1>Furnitures</h1>
            <Link href={"/products?category=furnitures"}>
              <Image src={"/images/category/furnitures.jpg"} alt="alt" width={300} height={300} />
            </Link>
          </div>
          <div className="card box">
            <h1>Cosmetics</h1>
            <Link href={"/products?category=cosmetics"}>
              <Image src={"/images/category/cosmetics.jpg"} alt="alt" width={300} height={300} />
            </Link>
          </div>
          <div className="card box">
            <h1>Fashion</h1>
            <Link href={"/products?category=fashion"}>
              <Image src={"/images/category/fashion.jpg"} alt="alt" width={300} height={300} />
            </Link>
          </div>
        </section>
        <section className="recommendation">
          <div className="best-sellers box">
            <h1>Best Sellers</h1>
            {randomProducts && (
              <SlickSlider
                items={randomItems}
                itemSize={{ width: 300, height: 200 }}
                actionType="Link"
                settings={
                  deviceEnv === "mobile"
                    ? {
                        slidesToShow: 1,
                        slidesToScroll: 1,
                      }
                    : deviceEnv === "tablet"
                    ? {
                        slidesToShow: 2,
                        slidesToScroll: 2,
                      }
                    : deviceEnv === "web"
                    ? {
                        slidesToShow: 3,
                        slidesToScroll: 3,
                      }
                    : {}
                }
              />
            )}
          </div>
          <div className="new-arrivals box">
            <h1>New Arrivals</h1>
            {recentProducts && (
              <SlickSlider
                items={recentItems}
                itemSize={{ width: 300, height: 200 }}
                actionType="Link"
                settings={
                  deviceEnv === "mobile"
                    ? {
                        slidesToShow: 1,
                        slidesToScroll: 1,
                      }
                    : deviceEnv === "tablet"
                    ? {
                        slidesToShow: 2,
                        slidesToScroll: 2,
                      }
                    : deviceEnv === "web"
                    ? {
                        slidesToShow: 4,
                        slidesToScroll: 4,
                      }
                    : {}
                }
              />
            )}
          </div>
        </section>
      </Main>
    </>
  );
}

const Main = styled.main`
  .banner {
    /* max-width: initial; */
    min-height: initial;
    .slick-slider {
      overflow-y: clip;
      .slick-list {
        overflow: visible;
        .slick-track {
          margin: 0;
        }
      }
    }
    .controller {
      pointer-events: none;
      position: absolute;
      top: 0;
      left: 50%;
      width: 100%;
      max-width: 1000px;
      height: 100%;
      transform: translateX(-50%);
      .arrow {
        pointer-events: initial;
      }
    }
  }

  .category {
    width: 100%;
    max-width: initial;
    margin: initial;
    min-height: initial;
    position: relative;

    padding: 100px 1rem;

    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(auto, 200px));
    justify-content: center;
    gap: 1rem;

    .card {
      height: 200px;
      border-radius: 10px;
      overflow: hidden;
      padding: 1rem;
      display: flex;
      flex-direction: column;
      transition: background-color 0.5s;

      a {
        height: 100%;
        overflow: hidden;
      }
    }

    @media (max-width: 500px), (width <= 500px) {
      display: flex;
      flex-direction: column;
      gap: 1rem;
    }
  }

  .recommendation {
    min-height: initial;
    display: flex;
    flex-direction: column;
    gap: 3rem;

    .best-sellers,
    .new-arrivals {
      border-radius: 10px;
      padding: 1rem;

      > h1 {
        padding: 1rem;
      }
      > :last-child {
        padding-bottom: 1rem;
      }
    }

    .best-sellers,
    .new-arrivals {
      .slick-slide {
        padding: 0 1rem;
        .img-outer {
          border-radius: 10px;
          overflow: hidden;
          &:hover {
            img {
              transform: scale(1.1);
            }
            .text {
              display: flex;
            }
          }

          img,
          .text {
            transition: all 0.5s;
          }
        }
        @media (max-width: 500px), (width <= 500px) {
          padding: 10px;
        }
      }
      .controller {
        .arrow {
          height: 5rem;
          border-radius: 50%;
        }
      }
    }
  }

  @media (max-width: 1000px) {
    .recommendation {
      .best-sellers,
      .new-arrivals {
        border-radius: initial;
      }
    }
  }
`;

// export async function getStaticPaths(context: any) {
//   return {
//     paths: [{ params: { id: "123" } }],
//     fallback: true,
//     // fallback: false,
//     // fallback: "blocking",
//   };
// }
